export const overviewStyles = `
  .energy-scene{position:relative;min-height:720px;overflow:hidden;border:1px solid #26414a;border-radius:26px;background:#c8e9f3;box-shadow:0 28px 80px #0008;isolation:isolate}
  .sky-layer{position:absolute;inset:0 0 120px;background:linear-gradient(180deg,#3a8bc0 0%,#8ed0e5 52%,#e9c594 100%);transition:background .8s}
  .scene-night .sky-layer{background:radial-gradient(circle at 75% 15%,#19365e 0,#091426 42%,#040a12 100%)}
  .scene-night .property-stage{filter:brightness(.54) saturate(.78) contrast(1.08) drop-shadow(0 25px 32px #0008)}
  .star-field{position:absolute;inset:0;opacity:0;transition:opacity .8s}.scene-night .star-field{opacity:1}.star-field i{position:absolute;left:var(--x);top:var(--y);width:2px;height:2px;border-radius:50%;background:#fff;box-shadow:0 0 8px #d8efff;animation:twinkle 2.6s var(--d) ease-in-out infinite}
  .shooting-star{position:absolute;left:20%;top:14%;width:90px;height:1px;background:linear-gradient(90deg,transparent,#fff);transform:rotate(-18deg);opacity:0}.scene-night .shooting-star{animation:shoot 14s 4s ease-in infinite}
  .celestial-arc{position:absolute;left:6%;right:6%;top:22px;height:210px}.arc-line{position:absolute;inset:12px 0 0;border-top:1px dashed #fff8;border-radius:50%}.celestial{position:absolute;translate:-50% -50%;font-style:normal;font-size:38px;color:#ffe86b;filter:drop-shadow(0 0 17px #ffdf4d);transition:left 1s,top 1s}.celestial.moon{color:#e7f4ff;filter:drop-shadow(0 0 15px #a6cfff)}
  .solar-clock{position:absolute;left:24px;top:22px;display:grid;padding:13px 15px;border:1px solid #ffffff40;border-radius:14px;background:#07131a80;backdrop-filter:blur(12px);color:#fff}.solar-clock strong{font-size:13px}.solar-clock span{font-size:11px;color:#d8edf1;margin-top:3px}.solar-clock small{font-size:10px;color:#b6d1d6;margin-top:7px}
  .bird{position:absolute;font-size:24px;font-style:normal;color:#122c35aa;animation:bird-fly 24s linear infinite}.bird-one{top:29%;left:-10%;animation-delay:-4s}.bird-two{top:22%;left:-10%;animation-delay:-15s;scale:.7}
  .aircraft{position:absolute;top:17%;left:-15%;color:#e6eff6;display:flex;align-items:center;filter:drop-shadow(0 2px 3px #0008);animation:plane 48s linear infinite}.aircraft span{font-size:25px;rotate:8deg}.aircraft i,.aircraft b{width:4px;height:4px;border-radius:50%;animation:blink 1s steps(1) infinite}.aircraft i{background:#ff334e}.aircraft b{background:#55ff88;animation-delay:.5s}
  .property-stage{position:absolute;inset:100px 0 86px;transition:filter .8s}.house-art{position:absolute;width:min(1120px,96%);height:100%;object-fit:contain;left:50%;bottom:-1%;transform:translateX(-50%);filter:drop-shadow(0 24px 28px #06101566)}
  .energy-flow-layer{position:absolute;inset:0;width:100%;height:100%;pointer-events:none}.flow-path{fill:none;stroke:#60798588;stroke-width:8;stroke-linecap:round}.flow-active{stroke:#55e7a5;filter:url(#glow);stroke-dasharray:.08 .05;animation:energy-pulse 1.6s linear infinite}.flow-grid.flow-active{stroke:#56d7f0}.flow-solar.flow-active{stroke:#ffe56e}.direction-out{animation-direction:reverse}
  .equipment-hit{position:absolute;z-index:3;border:1px solid #ffffff6b;border-radius:13px;padding:8px 11px;background:#07161ce6;color:#fff;box-shadow:0 8px 22px #0006;backdrop-filter:blur(10px);cursor:pointer;transition:transform .18s,border-color .18s}.equipment-hit:hover{transform:translateY(-3px);border-color:#5af0ac}.equipment-hit span{display:block;font-size:14px;font-weight:800}.equipment-hit small{display:block;color:#9cb7ba;font-size:9px;text-transform:uppercase;letter-spacing:.08em;margin-top:2px}
  .solar-hit{left:42%;top:17%}.grid-hit{left:5%;top:58%}.home-hit{left:42%;top:57%}.inverter-hit{right:18%;top:62%}.battery-hit{right:10%;top:73%}.battery-2{right:2%;top:73%}.ev-hit{right:7%;bottom:2%}
  .vehicle-shell{position:absolute;right:8%;bottom:11%;width:19%;height:12%;border-radius:55% 42% 20% 20%;box-shadow:inset 0 0 0 3px #9cb8c7,0 8px 15px #0005;pointer-events:none}
  .wind-instrument{position:absolute;right:25px;top:18px;display:grid;justify-items:center;padding:10px 13px;border:1px solid #ffffff4d;border-radius:15px;background:#06151bba;color:#fff}.wind-compass{width:40px;height:40px;border:1px solid #77919b;border-radius:50%;display:grid;place-items:center}.wind-compass i{font-style:normal;color:#5af0ac;transition:transform 1s}.wind-instrument strong{font-size:12px;margin-top:5px}.wind-instrument span{font-size:9px;color:#9eb4b8;text-transform:uppercase;letter-spacing:.1em}
  .summary-strip{position:absolute;left:14px;right:14px;bottom:14px;z-index:4;display:grid;grid-template-columns:repeat(5,1fr);gap:1px;overflow:hidden;border:1px solid #29464d;border-radius:16px;background:#20333a}.summary-strip div{padding:12px 14px;background:#09181ddf;backdrop-filter:blur(14px)}.summary-strip span{display:block;font-size:9px;color:#789295;text-transform:uppercase;letter-spacing:.1em}.summary-strip strong{display:block;margin-top:4px;font-size:14px;color:#effffc}
  .equipment-detail{position:absolute;z-index:8;right:22px;top:22px;width:min(330px,calc(100% - 44px));padding:22px;border:1px solid #365a62;border-radius:20px;background:#07161bf2;box-shadow:0 25px 70px #000a;backdrop-filter:blur(18px)}.equipment-detail>span{color:#5af0ac;font-size:9px;text-transform:uppercase;letter-spacing:.13em}.equipment-detail h2{margin:7px 0 4px;font-size:22px}.equipment-detail p{margin:0;color:#a8bec0}.detail-close{position:absolute;right:12px;top:10px;border:0;background:transparent;color:#fff;font-size:25px;cursor:pointer}
  @keyframes energy-pulse{to{stroke-dashoffset:-.26}}@keyframes twinkle{50%{opacity:.25;scale:.6}}@keyframes shoot{0%,72%{opacity:0;transform:translate(0,0) rotate(-18deg)}74%{opacity:1}80%,100%{opacity:0;transform:translate(480px,150px) rotate(-18deg)}}@keyframes bird-fly{to{left:110%}}@keyframes plane{0%,30%{left:-15%;opacity:0}32%{opacity:1}76%{opacity:1}78%,100%{left:115%;opacity:0}}@keyframes blink{50%{opacity:0}}
  @media(max-width:900px){.energy-scene{min-height:650px}.property-stage{inset:110px -80px 86px}.solar-hit{left:39%}.grid-hit{left:3%}.wind-instrument{right:12px}.summary-strip div{padding:11px 9px}}
  @media(max-width:600px){.energy-scene{min-height:610px;border-radius:18px}.property-stage{inset:125px -205px 102px}.solar-clock{left:12px;top:12px}.wind-instrument{right:10px;top:10px}.celestial-arc{height:150px}.summary-strip{grid-template-columns:repeat(3,1fr);bottom:10px;left:8px;right:8px}.summary-strip div:nth-child(4),.summary-strip div:nth-child(5){display:none}.equipment-hit{padding:6px 8px}.equipment-hit span{font-size:11px}.grid-hit{left:15%}.solar-hit{left:42%}.home-hit{left:43%}.inverter-hit{right:25%}.battery-hit{right:19%}.battery-2{right:8%}.ev-hit{right:15%}}
  @media(prefers-reduced-motion:reduce){.flow-active,.star-field i,.shooting-star,.bird,.aircraft,.aircraft i,.aircraft b{animation:none!important}.bird,.aircraft,.shooting-star{display:none}}
`;
